### PR TITLE
Update to Sunrise Framework v1.0.0-M4

### PR DESCRIPTION
**Pull request by lauraluiz**

### CODE REVIEW

**Review by katmatt — APPROVED** [review]
LGTM 👍

**Comment by lauraluiz** [comment]
@katmatt please review again. I've discovered that on the cart page the wishlist was always appearing empty, so I registered the mini-wishlist component. I had to register (and all the template name) on all the add/remove/clear controllers because they print content too on error 😞 

Added some missing NoCache annotations I detected and added the LogMetrics annotation for all (better that for some arbitrary chosen controllers).

I will apply those fixes to the framework app.

**Review by katmatt — APPROVED** [review]
Looks very good to me 👍 Should we then add the `MiniWishlistControllerComponent` to the app controllers in `commercetools-sunrise-java` too?

**Comment by lauraluiz** [comment]
Yes, as I mentioned in my last sentence ;)
So I will take care of that after merging this.

**Pull request merged**
